# Change these first
owner: BlackNetHome # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: IHDesign
    url: https://IHdesign.media
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true
status-website:
  baseUrl: /uptime # where "repo" is your repository name
  name: Uptime Status Website


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
